// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Local dev: file:./dev.db  |  Production: libsql://xxx.turso.io
    url: process.env["TURSO_DATABASE_URL"] ?? process.env["DATABASE_URL"] ?? `file:${process.cwd()}/dev.db`,
  },
});
